apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-configuration
  namespace: default
spec:
  type: configuration.redis
  metadata:
   - name: redisHost
     value: localhost:6379
   - name: redisDB
     value: 1