apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-state
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
   - name: redisHost
     value: localhost:6379
   - name: redisDB
     value: 0