apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-secrets
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ../secrets.json
  - name: nestedSeparator
    value: "."
  - name: multiValued
    value: "false"