apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: default
spec:
  mtls:
    enabled: false
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  nameResolution:
    component: "consul"
    configuration:
      selfRegister: true
      tags: 
        - "dapr"
      checks:
        - name: "Service Health Status"
          checkID: "serviceHealth:${APP_ID}"
          interval: "5s"
          http: "http://127.0.0.1:${APP_PORT}/health"
      meta:
        APP_ID: "${APP_ID}"
        APP_PORT: "${APP_PORT}"
        DAPR_HTTP_PORT: "${DAPR_HTTP_PORT}"
        DAPR_GRPC_PORT: "${DAPR_GRPC_PORT}"
        DAPR_METRICS_PORT: "${DAPR_METRICS_PORT}"